### ISSUE TITLE
Does literally nothing?

### ISSUE THREAD

**Issue by jD91mZM2** [erniebrodeur/ruby-beautify#39]
So, I decided to try it out....

And it seems to just be repeating whatever I say?
![image](https://cloud.githubusercontent.com/assets/12830969/24755481/b0c8f328-1ada-11e7-8866-90d62d6c77ac.png)

Am I just misunderstanding how to use this? :stuck_out_tongue:

**Comment by erniebrodeur** [comment]
A bit.   It's taking standard input and pushing it to standard output, that's a pretty typical feature of the commandline, but I should have that as an arg (will add that to the next version).

try adding -h to see the help list, or just use a filename as the first argument.

**Comment by LEGOlord208** [comment]
Oh, ok! I'll try1

**Comment by LEGOlord208** [comment]
Huh! That does nothing, either. 
![image](https://cloud.githubusercontent.com/assets/12830969/24826375/1657380c-1c35-11e7-8aa5-742c251f51b0.png)

**Comment by erniebrodeur** [comment]
It's designed to format a whole file, not a string of ;;;;;.   Try it on a reasonable sample and it'll 'do something'.

Thanks!
