### ISSUE TITLE
It does not seem to format erb if-else statements

### ISSUE THREAD

**Issue by interpegasus** [erniebrodeur/ruby-beautify#47]
## Issue
It looks like it formats if-else statements in erb files incorrectly. 
Please let me know if this can be fixed via a setting. Thanks

```
			<% if @user.errors[:username].any? %>
			<div class="field error">
				<% else %>
				<div class="field">
					<% end %>
```

**Comment by erniebrodeur** [comment]
Wasn't designed to format erb, that's a whole different bag of worms.   Maybe someday, but not anytime soon.
